import constants

if constants.JAP_DEV_FLAG:
    SONAR_USERNAME = """SONAR USERNAME"""
    SONAR_PASSWORD = """SONAR PASSWORD"""
else:
    SONAR_USERNAME = """SONAR USERNAME"""
    SONAR_PASSWORD = """SONAR PASSWORD"""



GITHUB_BEARER_TOKEN = """GITHUB BEARER TOKEN"""